version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo pre-build...
      - npm ci --include=dev
      -
  build:
    commands:
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - './node_modules/**/*'
