version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
      # - npm install yarn
  build:
    commands:
      - docker build -t aio/miko-nestjs .
  post_build:
    commands:
      - docker tag aio/miko-nestjs:latest 121323684128.dkr.ecr.us-east-1.amazonaws.com/aio-miko-nestjs:latest
      - docker push 121323684128.dkr.ecr.us-east-1.amazonaws.com/aio-miko-nestjs:latest
      - echo Writing image definitions file...
      - printf '[{"name":"aio-miko-nestjs-container","imageUri":"%s"}]' 121323684128.dkr.ecr.us-east-1.amazonaws.com/aio-miko-nestjs:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
